### ISSUE TITLE
Entities LocationGroup and Location miss some setters

### ISSUE THREAD

**Issue by vidompteur** [openwms/org.openwms.common.service#66]
To support easy implementation of a warehouse generation functionality some properties and service methods could be added.

LocationGroup to provide setters for property _account_.
Location does to provide setters for property _account_, _plcCode_, _description_, and _locationType_ (and some others).
LocationGroupService to provide a _save_ method.

If this was a misunderstanding by me or that feature should not be supported then just close that issue.
Otherwise I could provide the solution implementation if apreciated.

**Comment by openwms** [comment]
Hi @vidompteur . Many thanks for the recommendation. Indeed the `LocationGroup#save()` could be added in order to modify existing `LocationGroups`. About the setters I am not sure because those fields do not change. Usually `Locations` and `LocationGroups` are only created once as static reference data. A `Location` as well as a `LocationGroup` belongs always to one `Account`. The same for the `plcCode` and the type of `Location` - these never changes. For the descriptive text it makes sense to change this. So if you would like to create a PR for the save method and that one setter this would be great.

**Comment by vidompteur** [comment]
Sure, I will do that. Thanks for your feedback and thanks for sharing this great peace of software. Was really impressing for me how fast one could familiarize with it and get productive. 

Do I understand that right, that you expect, that the initial creation of all locations is done directly in the database, with DDL files, like import-DEMO.sql?
So, if I prefer to do that programatically, then I'd need all the setters for key fields or a constructor with all of them, is that right?

**Comment by openwms** [comment]
Well. the `DEMO` profile is used for the demo system on Heroku or if one would like to startup the service with demo data. But in a real project the service is not started in `DEMO` profile but the data is loaded via 3rd. party tools  and the service (as all other services) read and rely on that static data.
Setters are only necessary if you expect changes at runtime. For fields where no change is expected no Setter is needed. Following the Open-Closed principle
